kind: pipeline
type: docker
name: default

steps:
  - name: install-and-test
    image: cpp
    pull: never
    commands:
      - cmake -S . -B build
      - cmake --build "build"
      - ./build/Tests
